fail_fast: true

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml

  # For a platform agnostic hook use ->
  # - repo: https://github.com/koalaman/shellcheck-precommit
  #   rev: v0.11.0 # Use the latest stable version
  #   hooks:
  #     - id: shellcheck
  #       language: system
  #       files: ^scripts/.*\.sh$

  - repo: local
    hooks:
      - id: shell-check
        name: Shell Check
        entry: shellcheck
        language: system
        files: ^scripts/.*\.sh$
